{% set name = "dummy-0532" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dummy-0532-{{ version }}.tar.gz
  sha256: 93692df9fd669c8a33e63f1b242b0929697aa549efd4df5fffb0f3af48e2d8a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - branca
    - click
    - descartes
    - folium
    - geojson
    - geopandas
    - matplotlib-base
    - python >=3.7,<3.10
    - rasterio
    - requests
    - requests-oauthlib
    - tenacity
    - tqdm

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andher1802/dummy_0532.git
  summary: Dummy package for test
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
