{% set name = "dummy-0532" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8f4343664847ff6e14dc9295daf321dd8d657aa8a75d11e651e7e44075ae0b24

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - branca
    - click
    - descartes
    - folium
    - geojson
    - geopandas
    - matplotlib
    - python
    - rasterio
    - requests
    - requests-oauthlib
    - tenacity
    - tqdm
    - python >=3.7

test:
  imports:
    - up42

about:
  home: "https://github.com/andher1802/dummy_0532.git"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Dummy package for test"
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/andher1802/dummy_0532

extra:
  recipe-maintainers:
    - andher1802
